### PR TITLE
Skip intermediate function for internet points

### PR DESCRIPTION
**Pull request by fregante**
Does this work?

### CODE REVIEW

**Comment by jamiebuilds** [comment]
This kills the types

**Comment by fregante** [comment]
Isn’t there another way to add the types to an export?

**Comment by jamiebuilds** [comment]
is it important?

**Comment by fregante** [comment]
Is anything important? Isn’t the intent of this module to be as lightweight as possible?

**Comment by jamiebuilds** [comment]
> Is anything important?

shit dude i dont know

**Comment by fregante** [comment]
Seems doable:

```js
declare function defer(cb: () => mixed ): mixed;
```

https://stackoverflow.com/questions/44365093/flow-how-do-i-type-annotate-a-local-global-variable

https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKgCQoiAbgIb6gAmmkm+li7nLAXhyZcAFUIBbTLFS4e7YtGbZIqAHalCsNWw5cAFMQBGALlD6AlKAEA+UBMIAPTK1AWzD560oTYrVNCYAHSYjgAOsPi46Na6-ORAA

**Pull request closed without merging**
